language: elixir
elixir:
  - 1.6
otp_release:
  - 20.0
sudo: false

before_install:
- sudo add-apt-repository -y ppa:jonathonf/ffmpeg-3
- sudo apt-get update -qq
- sudo apt-get install -qq libswresample-dev
