language: elixir
elixir:
  - 1.6
otp_release:
  - 19.3
  - 20.0
sudo: false

before_install:
- sudo add-apt-repository ppa:mc3man/trusty-media -qq
- sudo apt-get update -qq
- sudo apt-get install -qq libswresample-dev
